version: 0.2
env:
    secrets-manager:
      TOKEN: thirdsecret:tokenforsonar
env:
  parameter-store:
    SNYK_AUTH_TOKEN: "snykAuthToken"
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:

#Static Application Security Scan (SAST scan) using SonarCloud
     - mvn verify sonar:sonar -Dsonar.projectKey=batumejavaprojectaws-12 -Dsonar.organization=batumejavaprojectaws-12 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN

#Quality Gates for Static Application Security Scan(SAST) using SonarCloud

     - sleep 5
     - |-
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=javaprojectaws-12 | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status";
#        if [ $quality_status = "ERROR" ] ; then exit 1;fi

#Software Composition Analysis Scan (SCA scan) using Snyk

     - |-
          apt-get update
          apt-get -y install maven 
          SNYK_AUTH_TOKEN: "snykAuthToken"
          mvn snyk:test  


#Dynamic Application Security Scan (DAST scan) using OWASP ZAP

     - |-
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y full-upgrade
          sudo apt-get -y autoremove
          apt-get -y install wget
          apt-get -y install default-jdk
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz 
          tar -xvf ZAP_2.14.0_Linux.tar.gz
          cd ZAP_2.14.0
          ./zap.sh -cmd -quickurl https://www.szonemaster.com/ -quickprogress -quickout ../zap_report.html

#Storing DAST Reports in S3 bucket

artifacts:
  files:
    - zap_report.html

